# Generated by Django 5.1.1 on 2025-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Связь жанра и произведения', 'verbose_name_plural': 'Связи жанров и произведений'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Расскажите о себе', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Код подтверждения для регистрации', max_length=32, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Укажите электронную почту', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['review', 'pub_date'], name='reviews_com_review__eef424_idx'),
        ),
        migrations.AddIndex(
            model_name='genretitle',
            index=models.Index(fields=['title', 'genre'], name='reviews_gen_title_i_1ce457_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['title', 'pub_date'], name='reviews_rev_title_i_bce0da_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'pub_date'], name='reviews_rev_author__133079_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name', 'year'], name='reviews_tit_name_6e08c7_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['category'], name='reviews_tit_categor_462c42_idx'),
        ),
    ]
