# Generated by Django 5.1.1 on 2025-11-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_temptitle_tempuser_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Отзыв'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TempTitle',
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
